# Generated by Django 5.0.1 on 2024-02-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unisteel', '0002_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rekviziti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='rekvizit')),
            ],
        ),
        migrations.AlterField(
            model_name='contacts',
            name='comment',
            field=models.TextField(default='No Comment'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact',
            field=models.CharField(max_length=50),
        ),
    ]
