# Generated by Django 5.0.1 on 2024-02-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unisteel', '0003_rekviziti_alter_contacts_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('number1', models.CharField(max_length=50)),
                ('number2', models.CharField(max_length=50)),
                ('number3', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Servises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='serviseImages/')),
                ('infoPreTitle', models.TextField()),
                ('infoTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('infoText', models.TextField()),
            ],
        ),
    ]
